add session storage file
lucyrose93/MakaTalk pull request #68
Opened 2017-07-25 20:03 UTC by lucyrose93

relates #67

@des-des feel free to merge, although I predict that you will have some helpful suggestions

I had to override the Lint pre-commit hook, as it complained that sessionStorage / location are not defined, even though they are browser features, right? 

Thanks in advance!

2017-07-26 15:15 UTC, des-des requested changes
Okay this looks good.

I think just clean it up a bit by pulling things you are using lots into there own variables, and giving ids more specific names.

I have not made comments at the end, but I think it should be clear

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +(function collectAnswers () {
At the top of this file:
```js
/* global: location, sessionStorage */
```
http://eslint.org/docs/user-guide/configuring#specifying-globals

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +    var yes = document.getElementById('yes')
`yes` is not a good name for an id. `agree-consent` would be better as yes is not specific enough for an id name

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +    var veryGood = document.getElementById('very-good')
again not good name for Id

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +  // pre-session responses
Here,
```js
var path = location.pathname.slice(1)
```

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +  if (location.pathname === '/today' ||
```js
if (path === 'today' || 
   path === 'last-week'
   ...) {

}
```

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +      sessionStorage.setItem((location.pathname).slice(1), 'very good')
sessionStorage.setItem(path, 'very good')

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +    var good = document.getElementById('good')
id name

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +      sessionStorage.setItem((location.pathname).slice(1), 'good')
(location.pathname).slice(1) -> path

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +    var ok = document.getElementById('ok')
same

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +      sessionStorage.setItem((location.pathname).slice(1), 'ok')
same

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +    var bad = document.getElementById('bad')
same

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +      sessionStorage.setItem((location.pathname).slice(1), 'bad')
same

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +    var veryBad = document.getElementById('very-bad')
same

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +      sessionStorage.setItem((location.pathname).slice(1), 'very bad')
same

2017-07-26 15:15 UTC, des-des commented on public/session-storage.js
> +  if (location.pathname === '/listen' ||
as above

2017-07-26 15:17 UTC, des-des commented
@lucyrose93 assign me when you want me to merge / review, sometimes I miss a notification, then will only look at the things that I am assigned to.

Also, sometimes I will assume that I do not need to look at something if I am not assigned

2017-07-26 16:10 UTC, lucyrose93 commented on public/session-storage.js
> +(function collectAnswers () {
OK

2017-07-26 16:12 UTC, lucyrose93 commented on public/session-storage.js
> +    var yes = document.getElementById('yes')
There is only one "yes" option in partials

It gets reused in different contexts (hence the if statements), so I can't make the id specific like "agree-consent"

Should it be a class then?

2017-07-26 16:12 UTC, lucyrose93 commented on public/session-storage.js
> +  // pre-session responses
makes sense :)

2017-07-26 16:12 UTC, lucyrose93 commented on public/session-storage.js
> +  if (location.pathname === '/today' ||
done

2017-07-26 16:12 UTC, lucyrose93 commented on public/session-storage.js
> +    var veryGood = document.getElementById('very-good')
☝️

2017-07-26 16:13 UTC, lucyrose93 commented on public/session-storage.js
> +      sessionStorage.setItem((location.pathname).slice(1), 'very good')
:)

2017-07-26 16:16 UTC, lucyrose93 commented
@des-des thanks for the feedback ✨ 
I have incorporated all changes
apart from the id names
please see my comment regarding this above
Ta!

2017-07-27 10:46 UTC, lucyrose93 commented
@des-des I have finished making changes. 

Please merge if happy with it. 

Thanks!

2017-07-27 12:17 UTC, des-des approved these changes

2017-07-27 12:17 UTC, merged