Clicking on the answers/buttons takes you to the proper landing pages
lucyrose93/MakaTalk pull request #80
Opened 2017-07-27 15:44 UTC by smarthutza

Clicking on the answers/buttons takes you to the proper landing pages

2017-07-27 16:27 UTC, des-des requested changes

2017-07-27 16:27 UTC, des-des commented on public/js/logic.js
> +})
hmm okay can you put all your js files in this directory, as right now you have some in `public` and some in `public/js` which is inconsistent.

2017-07-27 16:27 UTC, des-des commented on src/views/layout/default.hbs
>    <script src="./session-storage.js"></script>
Opts missed this but it is missing `type="text/javascript"`

2017-07-28 14:00 UTC, des-des requested changes

2017-07-28 14:00 UTC, des-des commented on public/js/logic.js
>  function changePage () {
okay this page is now duplicate

2017-07-28 17:33 UTC, lucyrose93 commented on public/js/logic.js
>  function changePage () {
sorted

2017-07-28 17:33 UTC, lucyrose93 commented
please merge @des-des

2017-07-29 16:33 UTC, des-des approved these changes

2017-07-29 16:33 UTC, des-des commented
@lucyrose93 okay can merge now, jus fix conflicts then re-assign

2017-08-07 13:42 UTC, lucyrose93 commented
thanks @des-des 
ready to merge

2017-08-07 14:52 UTC, merged