The player is functional on all pages
lucyrose93/MakaTalk pull request #98
Opened 2017-08-09 12:09 UTC by smarthutza

The player displays the right videos on each of the pages. 
There is some commented out code in the player.js file, but I will need it in the future. Please leave it there. 

Fix #97

2017-08-10 11:29 UTC, des-des approved these changes

2017-08-10 11:29 UTC, des-des commented on public/logic.js
> +  console.log('I have reached this line')
delete

2017-08-10 11:29 UTC, des-des commented on public/player.js
> +// 2. This code loads the IFrame Player API code asynchronously.
wrap this file in a iife

2017-08-10 11:30 UTC, des-des requested changes
ops see above

2017-08-14 10:43 UTC, lucyrose93 commented
@smarthutza you will need to merge this with master again when you address Eoin's feedback. 

Please try to make sure that it doesn't affect session storage and layout. To get an idea of how it should look, compare it with master at the moment, which has a nice layout :)

2017-08-15 20:48 UTC, lucyrose93 commented
I am closing this PR to replace it with an updated one that is merged with master

see https://github.com/lucyrose93/MakaTalk/pull/108

2017-08-15 20:48 UTC, closed without merging