image thumbnail layouts
lucyrose93/MakaTalk pull request #99
Opened 2017-08-09 18:16 UTC by lucyrose93

Added img sources to thumbnails

applied basic styles so the layout fits an iPad 2 (1024 x 678)

relates #82

please merge @des-des

2017-08-10 11:31 UTC, des-des requested changes

2017-08-10 11:31 UTC, des-des commented on public/css/master.css
> +/*#post-session-wrapper {
do you need to keep this?

If so leave a comment so I know

2017-08-10 15:45 UTC, lucyrose93 commented
@des-des Good point
not needed in this branch
Please merge now

2017-08-11 12:45 UTC, des-des approved these changes

2017-08-11 12:45 UTC, merged